### ISSUE TITLE
ImportError: cannot import name 'tzset' from 'time' when running redtide.py on Windows

### ISSUE THREAD

**Issue by angelotc** [qks1lver/redtide#4]
Looks like tzset is not available in Windows. 

**Workaround: Use Linux VM**

**Comment by eo1989** [comment]
I too just had this problem. Am looking through the code but am too new to this to know where/how to fix it.

**Comment by qks1lver** [comment]
Sorry about the late response @angelotc and thanks for seconding this @eo1989 I'll be looking into this. I have some Python codes that we have to run on Windows at work, and there are always a bit of complaint about libs that are not agnostic. I'll see what I can do with this issue. Thanks for the patience guys!

**Comment by eo1989** [comment]
Thank you for the quick answer! It was strange that I could get the data scraped using my mac but then couldn't duplicate the results on my win 10 pro desktop. Just for clarification, not sure if it's applicable, but on my mac it was ran using python 3.7.6, on my win 10 machine its python 3.8.1

**Comment by angelotc** [comment]
Either way, this is a godly script. I ended up using it with fbProphet to find trading strategies. It would be cool if there's a way to pull only materials etfs. Would be cool to categorize stocks.

**Comment by angelotc** [comment]
> I too just had this problem. Am looking through the code but am too new to this to know where/how to fix it.

Just create a Linux/Ubuntu  VM. Solved my problem.

**Comment by qks1lver** [comment]
@angelotc  @eo1989  Sorry about the wait. This should not be a problem anymore since the current version does use tzset anymore. I'm gonna close this ticket because tzset is not part of the code base now. Let me know if you see other problems. Thanks!
